# Site
name: "Jisen"
title: "Trust-Web"
description: "Internet And Technology. "
logo: 'file/ic.png'
favicon: 'file/1_20201008_102711_0000.png'
baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'trust-web-github-io'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: kek234600@gmail.com

# Authors
authors:
  sal:
    name: Jisen
    display_name: Jisen
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: kek234600@gmail.com
    web: https://trust-web.github.io/
    twitter: https://twitter.com/wowthemesnet
    description: "网站的主要建设者。"
  john:
    name: Chender
    display_name: Chender    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://www.coolapk.com/u/2282697
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Gitalk
gitalk:
  clientID: 7e24fdd4a6823c834977
  clientSecret: 3a0b43b13d271c2079b567376325b4f843d0c52a
  repo: trust-web.github.io
  owner: trust-web


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
